# Use XDG spec with ssh, ultimately gave up on this beacause i need SFTP clients to work,
# some allow to configure custom private key locations but other don't.
Host *
    # IdentityFile       ${XDG_DATA_HOME}/ssh/id_rsa
    # IdentityFile       ${XDG_DATA_HOME}/ssh/id_dsa
    # IdentityFile       ${XDG_DATA_HOME}/ssh/id_ecdsa
    # IdentityFile       ${XDG_DATA_HOME}/ssh/id_ed25519
    # UserKnownHostsFile ${XDG_DATA_HOME}/ssh/known_hosts
