#!/bin/bash

# Directories
alias \
    src="cd $HOME/.local/src/ && ls" \
    cfg="cd $HOME/.config/ && ls" \
    tmp="cd $HOME/Desktop/temp/ && ls" \
    dsk="cd $HOME/Desktop/ && ls" \
    prj="cd $HOME/Documents/projects/ && ls" \
    doc="cd $HOME/Documents/ && ls" \
    dow="cd $HOME/Downloads/ && ls" \
    mus="cd $HOME/Music/ && ls" \
    prt="cd $HOME/Pictures/Screenshots/ && ls" \
    bkg="cd $HOME/Pictures/Backgrounds/ && ls" \
    img="cd $HOME/Pictures/ && ls" \
    vid="cd $HOME/Videos/ && ls" \

# Common
alias \
    ls="exa -al --group-directories-first" \
    fzf="fzf --cycle --reverse" \
    diff="diff --color=auto" \
    grep="grep --color=auto" \
    calc="bc -l" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -iv" \
    vim="nvim" \

# Command shortcuts
alias \
    apt-upgrade="sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y" \
    df-short="df -h | grep -v '\s/dev.*$\|\s/run.*$\|\s/boot.*$'" \
    wacom-setup-menu="wacom-setup menu" \
    notes="note list" \
    def="dict" \

# Launch args
alias \
    fzf-edit-script="fzf_nav /home/$(whoami)/.config/scripts" \
    newsboat="newsboat -u ~/Documents/personal/rss" \
