#!/bin/bash

# Common
alias \
    ls="exa -al --group-directories-first" \
    fzf="fzf --cycle --reverse" \
    diff="diff --color=auto" \
    grep="grep --color=auto" \
    calc="bc -l" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -iv" \
    vim="nvim" \

# Directories
alias \
    apt-upgrade="sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y" \
    tmp="cd $HOME/Desktop/local/temp/ && ls" \
    www="cd $HOME/Desktop/www/ && ls" \
    dsk="cd $HOME/Desktop/ && ls" \
    dow="cd $HOME/Downloads/ && ls" \
    prj="cd $HOME/Projects/ && ls" \
    prt="cd $HOME/Media/Pictures/Screenshots/ && ls" \
    bkg="cd $HOME/Media/Pictures/Backgrounds/ && ls" \
    img="cd $HOME/Media/Pictures/ && ls" \
    vid="cd $HOME/Media/Videos/ && ls" \
    mus="cd $HOME/Media/Music/ && ls" \
    src="cd $HOME/.local/src/ && ls" \
    cfg="cd $HOME/.config/ && ls" \

# Launch args
alias \
    fzf-edit-script="fzf_nav /home/$(whoami)/.config/scripts" \
    newsboat="newsboat -u ~/Documents/personal/rss" \
    notes="note list" \
    def="dict" \
