#!/bin/bash
# Useful variables

# Custom PATHs for executables
PATH="$HOME/.config/scripts/status${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/menu${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/menu/xclipmenu${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/sway${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/dwm${PATH:+:${PATH}}"
PATH="$HOME/.config/wrappers${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts${PATH:+:${PATH}}"
PATH="$HOME/.local/bin${PATH:+:${PATH}}"
#PATH="/usr/local/plan9/bin${PATH:+:${PATH}}"

# Common
export \
    HISTIZE= \
    HISTFILESIZE= \
    GITLAB="ssh://git@gitlab.com/tavo-wasd" \
    BOOKMARKS="$HOME/Documents/bookmarks" \
    BIB="$HOME/Documents/bibliography" \
    WEEK=$(date '+%U') \
    DATE=$(date -I) \
    COLUMNS=120 \

# Default programs
export \
    TERM="xterm-256color" \
    OPENER="xdg-open" \
    READER="zathura" \
    BROWSER="firefox" \
    TERMINAL="foot" \
    EDITOR="nvim" \
    VISUAL="nvim" \
    IMAGE="swayimg" \
    VIDEO="mpv" \

# Theming
export \
    QT_QPA_PLATFORMTHEME="qt5ct" \
    GTK_THEME="Materia:dark" \

# Clipboard
export \
    CM_SELECTIONS="clipboard" \
    CM_MAX_CLIPS=10 \

export \
    MOZILLA_CERTIFICATE_FOLDER="$HOME/.local/share/mozilla/.mozilla/firefox/p2uualdb.default"
