#!/bin/sh

case $- in
    *i*) ;;
      *) return;;
esac

PATH="$HOME/.config/scripts/status${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/menu${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/menu/xclipmenu${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/sway${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/dwm${PATH:+:${PATH}}"
PATH="$HOME/.config/wrappers${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts${PATH:+:${PATH}}"
PATH="$HOME/.local/bin${PATH:+:${PATH}}"
#PATH="/usr/local/plan9/bin${PATH:+:${PATH}}"

export \
    HISTIZE= \
    HISTFILESIZE= \
    DATE=$(date -I) \
    WEEK=$(date '+%U') \

export \
    TERM="xterm-256color" \
    EDITOR="nvim" \
    VISUAL="nvim" \

export \
    QT_QPA_PLATFORMTHEME="qt5ct" \
    CM_SELECTIONS="clipboard" \
    GTK_THEME="Materia:dark" \
    CM_MAX_CLIPS=10 \

export \
    GITLAB="ssh://git@gitlab.com/tavo-wasd" \
    BOOKMARKS="$HOME/Documents/bookmarks" \
    BIB="$HOME/Documents/bibliography" \

git_branch() {
    GIT_BRANCH="$(git branch 2>/dev/null | sed '/\*/!d;s/^\*\s*//g;s/\s*$//g')"
    [ -n "$GIT_BRANCH" ] && printf "%s " "$GIT_BRANCH"
}

TIME="$(date)"
TIME=${TIME% [AP]M*}
TIME=${TIME##* }

PS1='\
$(tput dim)($?)$(tput sgr0) \
$(tput bold)$(tput setaf 6)${USER:=$(id -un)}$(tput sgr0)\
$(tput setaf 6)@${HOSTNAME:=$(hostname -s)}$(tput sgr0) \
$(tput setaf 4)${PWD} \
$(tput bold)$(tput setaf 5)$(git_branch)$(tput sgr0)\
$(tput dim)[!] ${TIME}$(tput sgr0)
$(tput dim)$(if (( USER_ID )); then print \$; else print \#; fi)$(tput sgr0) \
'

export \
    XDG_STATE_HOME="$HOME/.local/state" \
    XDG_CACHE_HOME="$HOME/.local/cache" \
    XDG_DATA_HOME="$HOME/.local/share" \
    XDG_CONFIG_HOME="$HOME/.config" \
    _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java" \
    GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0" \
    PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store" \
    VIMINIT="source $XDG_CONFIG_HOME/vim/vimrc" \
    XSERVERRC="$XDG_CONFIG_HOME/X11/xserverrc" \
    XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" \
    HISTFILE="$XDG_STATE_HOME/bash_history" \
    XINITRC="$XDG_CONFIG_HOME/X11/xinitrc" \
    LESSHISTFILE="$XDG_DATA_HOME/lesshst" \
    ELECTRUMDIR="$XDG_DATA_HOME/electrum" \
    CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv" \
    WINEPREFIX="$HOME/.local/share/wine" \
    WGETRC="$HOME/.config/wget/wgetrc" \
    GOPATH="$XDG_DATA_HOME/go" \

alias \
    wget="wget --hsts-file=$XDG_DATA_HOME/wget/wget-hsts"

alias \
    src="cd $HOME/.local/src/ && ls" \
    cfg="cd $HOME/.config/ && ls" \
    tmp="cd $HOME/Desktop/temp/ && ls" \
    dsk="cd $HOME/Desktop/ && ls" \
    prj="cd $HOME/Desktop/projects/ && ls" \
    doc="cd $HOME/Documents/ && ls" \
    dow="cd $HOME/Downloads/ && ls" \
    mus="cd $HOME/Music/ && ls" \
    prt="cd $HOME/Pictures/Screenshots/ && ls" \
    bkg="cd $HOME/Pictures/Backgrounds/ && ls" \
    img="cd $HOME/Pictures/ && ls" \
    vid="cd $HOME/Videos/ && ls" \

alias \
    ls="exa -al --icons --group-directories-first --no-permissions --no-user --time-style=iso --git" \
    fzf="fzf --cycle --reverse" \
    diff="diff --color=auto" \
    grep="grep --color=auto" \
    calc="bc -l" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="trash" \
    vim="nvim" \
    mgr-all="mgr pacman_upgrade apt_upgrade flatpak_update distrobox_update pip_update configs passmgr" \
    df-short="df -h | grep -v '\s/dev.*$\|\s/run.*$\|\s/boot.*$'" \
    qr-png="qrencode -s 16 -o qr.png" \
    qr="qrencode -t ansiutf8" \
    clip="xsel -ib" \

[ -f ~/.config/shell/posix-kit ] && . ~/.config/shell/posix-kit
[ -f ~/.config/shell/dwm ]       && . ~/.config/shell/dwm

command -v fetch >/dev/null 2>&1 && fetch min
