#!/bin/sh
# $ printf '#!/bin/sh\n\n[ -f ~/.config/X11/xinitrc ] && . ~/.config/X11/xinitrc || . /etc/X11/Xsession\n' | sudo tee /etc/X11/xinit/xinitrc

userresources=$XDG_CONFIG_HOME/X11/Xresources
ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

[ -d /etc/X11/xinit/xinitrc.d ] &&
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do [ -x "$f" ] && . "$f" ; done &&
    unset f

# Added xinitrc config
dbus-update-activation-environment --systemd --all &
systemctl --user import-environment DISPLAY &
xset r rate 300 70 &
setxkbmap en &
dwmblocks &
clipmenud &
dunst &
picom --experimental-backends --animation-for-open-window=zoom &
emacs --daemon &
dropbox &
clear &

# Multiple displays, add this into xinitrc.displays:
# xrandr --output DVI-D-0 --right-of HDMI-0
[ -f "$HOME/.config/X11/xinitrc.displays" ] && . /home/tavo/.config/X11/xinitrc.displays
xsetroot -solid '#1e2326' &
sleep 0.2

while true; do
	dwm >/dev/null 2>&1
done

exec dwm

. /etc/X11/Xsession
