#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

[ -d /etc/X11/xinit/xinitrc.d ] &&
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do [ -x "$f" ] && . "$f" ; done &&
    unset f

# Added xinitrc config
dbus-update-activation-environment --systemd --all &
systemctl --user import-environment DISPLAY &
hsetroot -cover /home/tavo/Pictures/Backgrounds/default.jpeg &
xset r rate 300 50 &
setxkbmap en &
dwmblocks &
clipmenud &
dunst &
clear &

while true; do
	dwm >/dev/null 2>&1
done

exec dwm

