#!/bin/sh
# `/etc/X11/xinit/xinitrc`:
#
# #!/bin/sh
# if [ -f ~/.config/X11/xinitrc ] ; then
#     . ~/.config/X11/xinitrc
# else
#     . /etc/X11/Xsession
# fi

userresources=$XDG_CONFIG_HOME/X11/Xresources
ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ] ; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ] ; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ] ; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ] ; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [ -d ~/.config/X11/init.d ] ; then
    for f in ~/.config/X11/init.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

while true; do
	dwm >/dev/null 2>&1
done
