#!/bin/sh

opts="0=none 900=15min 1800=30min 3600=1h 7200=2h 14400=4h 28800=8h 43200=12h 86400=24h"

time="$(for o in $opts; do
  printf '%s\n' "$o"
done | menu 'dmenu' 'x11 screen standby time (seconds)')"
time="${time%%=*}"

if [ "$time" != "" ]; then
  xset dpms "$time"
fi
