- manager: cargo
  depends:
    - cargo
  remotes:
    - remote: all
      tasks:
        - task: update-all
          cmd: $HOME/.config/pm/cargo/update.sh
      packages:
        - package: "typstyle"
