#!/bin/sh
# shellcheck disable=SC2123

PATH="$HOME/.config/scripts/status${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/menu${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/menu/xclipmenu${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/sway${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/dwm${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/x11${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts/setup${PATH:+:${PATH}}"
PATH="$HOME/.config/wrappers${PATH:+:${PATH}}"
PATH="$HOME/.config/scripts${PATH:+:${PATH}}"
PATH="$HOME/.local/bin${PATH:+:${PATH}}"
PATH="$HOME/.local/state/nix/profile/bin${PATH:+:${PATH}}"
PATH="$HOME/.config/emacs/bin${PATH:+:${PATH}}"
PATH="$HOME/.local/share/go/bin${PATH:+:${PATH}}"
PATH="/usr/local/go/bin${PATH:+:${PATH}}"
PATH="$HOME/.local/share/pyenv/shims${PATH:+:${PATH}}"
PATH="$HOME/.local/share/cargo/bin:$PATH"
PATH="/opt/nvim-linux-x86_64/bin:$PATH"
