#!/bin/sh
TARGET="nvm"

if [ -s "$NVM_DIR/nvm.sh" ] && ! [ "$NVM_LOADED" ]; then
  NVM_LOADED=1
  . "$NVM_DIR/nvm.sh"
fi

wrapper="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/$(basename "$0")"

prog="$(command -v "$TARGET")"
if diff "$prog" "$wrapper" >/dev/null 2>&1; then
  echo "'$TARGET' not found in PATH" >&2
  exit 1
fi

"$prog" "$@"
