#!/bin/sh

set -eu

: "${GS_WIDTH:=1920}"
: "${GS_HEIGHT:=1080}"
: "${GS_FPS:=60}"
: "${GS_HDR:=false}"

set -- \
  -f \
  -e \
  -w "$GS_WIDTH" \
  -h "$GS_HEIGHT" \
  -W "$GS_WIDTH" \
  -H "$GS_HEIGHT" \
  -r "$GS_FPS"

case "$GS_HDR" in
true | TRUE | True | 1)
  set -- "$@" --hdr-enabled
  ;;
esac

exec gamescope "$@" -- steam -gamepadui
