" XDG Specifications
let rtp=&runtimepath
set runtimepath=~/.config/vim
let &runtimepath.=','.rtp.',~/.config/vim/after'
set directory=~/.config/vim/swap//,.,~/tmp,/var/tmp,/tmp
set backupdir=~/.config/vim/backup//,.,~/tmp,~/
set spellfile=~/.config/vim/spell/en.utf-8.add
set viminfo+=n~/.config/vim/viminfo
set viewdir=~/.config/vim/view/
set undodir=~/.config/vim/undo//,.

" Preferences
let mapleader = "\<Space>"
set list listchars=tab:⎸\ ,trail:~
set clipboard=unnamedplus
set shellcmdflag=-c
set encoding=utf-8
set relativenumber
filetype plugin on
set shiftwidth=4
set nocompatible
set cursorline
set ignorecase
set expandtab
set smartcase
set autoread
set wildmenu
set hlsearch
set swapfile
set undofile
set mouse=a
set showcmd
set number
syntax on

if (empty($TMUX) && getenv('TERM_PROGRAM') != 'Apple_Terminal')
    if (has("nvim"))
        let $NVIM_TUI_ENABLE_TRUE_COLOR=1
    endif
    if (has("termguicolors"))
        set termguicolors
    endif
endif

" Keybinds
noremap <F5> :setlocal spell! spelllang=en<CR>
noremap <F6> :setlocal spell! spelllang=es<CR>
noremap <F8> :TagbarToggle<CR>
noremap <C-e> !!$SHELL<CR>
noremap <tab> :bn<CR>
noremap <C-c> :bd<CR>
noremap <C-s> :w<CR>
noremap <A-h> 5<C-w><
noremap <A-j> 5<C-w>-
noremap <A-k> 5<C-w>+
noremap <A-l> 5<C-w>>
noremap H :nohl<CR>
noremap <leader><Space> za

" QuickFix
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow
autocmd QuickFixCmdPost     * if &ft ==# 'qf' | wincmd J | endif

function! WrapQuickfixNext()
    try
        execute 'cnext'
    catch /^Vim\%((\a\+)\)\=:E553/
        cfirst
    endtry
endfunction
function! WrapQuickfixPrev()
    try
        execute 'cprevious'
    catch /^Vim\%((\a\+)\)\=:E553/
        clast
    endtry
endfunction

nnoremap <silent> <Leader>n :call WrapQuickfixNext()<CR>
nnoremap <silent> <Leader>p :call WrapQuickfixPrev()<CR>
nnoremap <leader>m :make<CR><CR>
nnoremap <F9> :make<CR><CR>

function! SetMakeprg()
    if filereadable('Makefile')
        set makeprg=make
    else
    endif
endfunction
autocmd VimEnter * call SetMakeprg()

" c/c++
autocmd FileType c :compiler gcc | setlocal makeprg=gcc\ -Wall\ -c\ %
autocmd FileType cpp :compiler gcc | setlocal makeprg=g++\ -Wall\ -c\ %

" groff
autocmd FileType groff noremap <buffer> <silent> <F9> :!zathura --fork %:r.pdf<CR> & disown
autocmd FileType groff noremap <buffer> <C-s> :w<CR> :!groffc %<CR><CR>
au BufNewFile,BufRead *.ms set filetype=groff

" Python
autocmd FileType python noremap <buffer> <F9> :!python %<CR>

" Functions

"Open a shell on a vertical split
set splitright
function OpenTerminal()
    execute "normal \<C-l>"
    execute "normal \<C-l>"
    execute "normal \<C-l>"
    execute "normal \<C-l>"

    let bufNum = bufnr("%")
    let bufType = getbufvar(bufNum, "&buftype", "not found")

    if bufType == "terminal"
        execute "q"
    else
        execute "bot sp term://bash"
        execute "resize -8"
        execute "set nonu"
        execute "set nornu"
        silent au BufLeave <buffer> stopinsert!
        silent au BufWinEnter,WinEnter <buffer> startinsert!
        execute "tnoremap <buffer> <C-h> <C-\\><C-n><C-w><C-h>"
        execute "tnoremap <buffer> <C-t> <C-\\><C-n>:q<CR>"
        execute "tnoremap <buffer> <C-\\><C-\\> <C-\\><C-n>"
        execute "IndentLinesDisable"

        startinsert!
    endif
endfunction
nnoremap <C-t> :call OpenTerminal()<CR>

" Plugins
if empty(glob('~/.config/vim/autoload/plug.vim'))
    silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source '~/.config/vim/vimrc'
endif

call plug#begin()
Plug 'instant-markdown/vim-instant-markdown'
Plug 'vim-airline/vim-airline-themes'
Plug 'norcalli/nvim-colorizer.lua'
Plug 'vim-scripts/AutoComplPop'
Plug 'vim-airline/vim-airline'
Plug 'ryanoasis/vim-devicons'
Plug 'airblade/vim-gitgutter'
Plug 'rhysd/vim-clang-format'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-commentary'
Plug 'Yggdroot/indentLine'
Plug 'preservim/nerdtree'
Plug 'ibhagwan/fzf-lua'
Plug 'preservim/tagbar'
" Plug 'morhetz/gruvbox'
Plug 'sainnhe/gruvbox-material'
call plug#end()

" gruvbox-material
set background=dark
let g:gruvbox_material_background = 'hard'
colorscheme gruvbox-material

" AutoComplPop
inoremap <expr> <Tab> pumvisible() ? "<C-y>" : "<Tab>"
set completeopt=menuone,longest
set complete+=kspell

" Airline
let g:airline#extensions#tabline#buffer_min_count = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
set ttimeout ttimeoutlen=0
set laststatus=2
set noshowmode

" NERDTree
nnoremap <C-f> :NERDTreeToggle<CR>

" IndentLine
let g:indentLine_enabled = 1
let g:indentLine_char = '⎸'

" fzf-lua
noremap <A-b> :FzfLua git_branches<CR>
noremap <A-c> :FzfLua git_commits<CR>
noremap <A-s> :FzfLua git_status<CR>
noremap <A-f> :FzfLua files<CR>
noremap gb :FzfLua git_branches<CR>
noremap gs :FzfLua git_status<CR>
noremap gf :FzfLua files<CR>

" git-gutter
highlight GitGutterChange guifg=#83a598 ctermfg=3
highlight GitGutterDelete guifg=#fb4934 ctermfg=1
highlight GitGutterAdd    guifg=#b8bb26 ctermfg=2
highlight SignColumn guibg=NONE ctermbg=NONE
let g:gitgutter_set_sign_backgrounds = 1
noremap gd :GitGutterToggle<CR>
set signcolumn=yes
set updatetime=100

" Instant Markdown
let g:instant_markdown_autostart = 0
autocmd FileType markdown noremap <buffer> <silent> <F9> :InstantMarkdownPreview<CR>
let g:instant_markdown_browser = "firefox --new-window"
let g:instant_markdown_mathjax = 1
let g:instant_markdown_mermaid = 1
