- manager: apt-get
  depends:
    - apt-get
  remotes:
    - remote: all
      cli:
        - task: sync
          cmd: apt-get update
          privileged: true
        - task: update-all
          cmd: apt-get full-upgrade -y
          privileged: true
      packages:
        list: list.yml
