- manager: npm
  depends:
    - npm
  remotes:
    - remote: npm
      tasks:
        - task: update-all
          cmd: $HOME/.config/pm/npm/update.sh
      packages:
        - package: "@ast-grep/cli"
        - package: "@openai/codex"
        - package: "neovim"
        - package: "@mermaid-js/mermaid-cli"
