env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24

$mod = SUPER

$left = h
$down = j
$up = k
$right = l

$term = foot
$menu = bemenu-run -p "Run" | xargs -r hyprctl dispatch exec
$power = printf 'poweroff\nreboot\n' | bemenu -p Power | xargs sh -c
$pass = find "$PASSWORD_STORE_DIR" -type f -name '*.gpg' | sed -e "s#^$PASSWORD_STORE_DIR/##" -e 's#\\.gpg$##' | bemenu -p "Pass" | xargs -r pass | head -n 1 | tr -d '\n' | wtype -
$passotp = find "$PASSWORD_STORE_DIR" -type f -name '*.gpg' | sed -e "s#^$PASSWORD_STORE_DIR/##" -e 's#\\.gpg$##' | bemenu -p "Pass" | xargs -r pass otp | head -n 1 | tr -d '\n' | wtype -
$sound = foot -T floating-wiremix wiremix
$wifi = foot -T floating-impala impala
$bluetooth = foot -T floating-bluetui bluetui
$email = thunderbird
$browser = ${BROWSER:-firefox}
$volup = wpctl set-volume @DEFAULT_SINK@ 5%+ && wpctl set-mute @DEFAULT_SINK@ 0
$voldown = wpctl set-volume @DEFAULT_SINK@ 5%- && wpctl set-mute @DEFAULT_SINK@ 0
$mute = wpctl set-mute @DEFAULT_SINK@ toggle
$micup = wpctl set-volume @DEFAULT_SOURCE@ 5%+ && wpctl set-mute @DEFAULT_SOURCE@ 0
$micdown = wpctl set-volume @DEFAULT_SOURCE@ 5%- && wpctl set-mute @DEFAULT_SOURCE@ 0
$micmute = wpctl set-mute @DEFAULT_SOURCE@ toggle
$brightup = brightnessctl s 5%+
$brightdown = brightnessctl s 5%-
$prt = grim -g "$(slurp -d)" - | tee "${XDG_PICTURES_DIR:-$HOME/Pictures}/Screenshots/$(date +%Y%m%d%H%M%2N).png" | wl-copy -t image/png
$colorpicker = grim -g "$(slurp -p)" -t ppm - | magick - -format '%[pixel:p{0,0}]' txt:- | sed '/^#/d;s/^.*#/#/;s/ .*$//' | tr '[:upper:]' '[:lower:]' | tr -d '\n' | wl-copy
