# See https://wiki.hypr.land/Configuring/Master-Layout/ for more

general {
    layout = master
}

master {
    new_status = slave
    new_on_top = false
}

bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, layoutmsg, cycleprev
bind = $mod, J, layoutmsg, cyclenext
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

bind = $mod SHIFT, H, layoutmsg, mfact -0.05
bind = $mod SHIFT, L, layoutmsg, mfact +0.05
bind = $mod SHIFT, K, layoutmsg, swapprev
bind = $mod SHIFT, J, layoutmsg, swapnext
