source = ~/.config/hypr/00-monitors.conf
source = ~/.config/hypr/01-vars.conf
source = ~/.config/hypr/02-binds.conf
source = ~/.config/hypr/03-kb.conf
source = ~/.config/hypr/04-mouse.conf
source = ~/.config/hypr/50-master.conf
# source = ~/.config/hypr/50-scrolling.conf
source = ~/.config/hypr/90-laptop.conf
source = ~/.config/hypr/90-appearance.conf
source = ~/.config/hypr/90-misc.conf
source = ~/.config/hypr/99-autostart.conf
