#!/bin/sh
# Set default output device

# Get proper name from sinks
output=$(pactl list short sinks | cut -f 2 | menu "dmenu" "Output:")

# Set audio device, notify command success
pactl set-default-sink "$output"

# Reload statusbar module (dwm & dwmblocks)
if pidof dwmblocks >/dev/null; then
	kill -44 "$(pidof dwmblocks)"
fi
