#!/bin/sh
PROMPT="$1" MODE="$2"
if [ "$PROMPT" = "" -o "$PROMPT" = "-h" ] ; then printf "Usage: menu [prompt] [run/pass]\n" ; return 0 ; fi
[ "$MODE" = "pass" ] && BPASS="-x" DPASS="-P"
BRUN="-run" DRUN="_run" TRUN="-run" FRUN=""
[ "$MODE" != "run" ] && BRUN="" DRUN="" TRUN="" FRUN=""

# Configuration
menu="menu_dmenu"
font="JetbrainsMono"
font_size="10"
col_white="#ebdbb2" # White
col_nb="#121212"    # Normal background
col_nf="#606060"    # Normal foreground
col_sb="#fabd2f"    # Selected background
col_sf="#121212"    # Selected foreground

menu_bemenu() {
bemenu$BRUN \
    --no-exec \
    -i \
    -c \
    -l 10 \
    -W 0.4 \
    -B 2 \
    --cw 1 \
    --tb $col_sb \
    --tf $col_sf  \
    --fb $col_nb  \
    --ff $col_nf  \
    --cb $col_nb  \
    --cf $col_white \
    --nb $col_nb  \
    --nf $col_nf  \
    --hb $col_sb  \
    --hf $col_sf  \
    --ab $col_nb  \
    --af $col_nf  \
    --bdr $col_sb  \
    --fn "$font $font_size"  \
    -p "$PROMPT" \
    $BPASS
}

menu_dmenu() {
dmenu$DRUN \
    -i \
    -l 10 \
    -nb $col_nb \
    -nf $col_nf \
    -sb $col_sb \
    -sf $col_sf \
    -fn "$font:size=$font_size" \
    -p "$PROMPT" \
    $DPASS
}

menu_tofi() {
tofi$TRUN \
    --prompt-text "$PROMPT"
}

menu_fzf() {
fzf \
    --cycle \
    --reverse
}

$menu
