#!/bin/sh
# Prompt for power options using dmenu

option=$(printf "Shutdown\nRestart\nLog out" | ~/.config/scripts/menu/menu "Power:")

slogout() {
    killall xinit
    swaymsg exit
}

case "$option" in
	"Shutdown") systemctl poweroff ;;
	"Restart") systemctl reboot ;;
	"Log out") pkill xinit;;
	*) exit 1 ;;
esac

