#!/bin/sh

options="󰀻:Run 󰌾:Password 󰕾:Output 󰍬:Input 󰱱:Emoji 󰃀:Open_Bookmark 󰆏:Copy_Bookmark 󰐥:Power"
separator=" "

chosen="$(for o in $options; do
  printf '%s%s%s\n' "${o%%:*}" "$separator" "${o##*:}"
done | menu dmenu '')"
chosen="${chosen#*"$separator"}"

case "$chosen" in
Run) menu "run" "" ;;

Password) menu-pass-gtype ;;

Output) menu-output ;;
Input) menu-input ;;

Emoji) menu-emoji-copy ;;

Open_Bookmark) menu-bookmarks-open ;;
Copy_Bookmark) menu-bookmarks-copy ;;

Power) menu-power ;;

*) ;;
esac
