#!/bin/sh
# menu for 'pass'
PASSWORD_STORE_DIR="$HOME/.password-store"
MENU="$HOME/.config/scripts/menu/menu"

password="$(find "$PASSWORD_STORE_DIR" -type f -name '*.gpg' | sed "s@$PASSWORD_STORE_DIR/@@g ; s@.gpg@@g" | $MENU "Pass:")"

! [ -z "$password" ] && printf '%s' "$password"
