managers:
  - id: "apt-get"
    depends:
      - "apt-get"
    remotes:
      - id: "trixie"
        cli:
          - intent: "update-all"
            description: "Update all installed trixie applications"
            cmd: "apt-get update -y"
            privileged: true
