#!/bin/sh
PKG_LIST="${PKG_LIST:-$XDG_CONFIG_HOME/packages/cargo/list}"

if ! [ -f "$PKG_LIST" ]; then
  echo "No package list found at PKG_LIST=$PKG_LIST"
  exit 1
fi

while read l; do
  pkg="${l%%#*}"
  if [ "$pkg" != "" ]; then
    cargo install "$pkg" --locked
  fi
done <"$PKG_LIST"
