#!/bin/sh
NVIM_PREFIX="${NVIM_PREFIX:-"/usr/local"}"

archive="nvim-linux-x86_64.tar.gz"
latest="https://github.com/neovim/neovim/releases/latest/download/$archive"

die() {
  errMsg="$1"
  tmpFile="$2"

  echo "$errMsg"

  if [ -f "$tmpFile" ]; then
    rm -rf "$tmpFile"
  fi

  exit 1
}

if ! [ -d "$NVIM_PREFIX" ]; then
  die "invalid installation prefix (\$NVIM_PREFIX=$NVIM_PREFIX)"
fi

tmp="$(mktemp)" ||
  die "failed to create tmpfile"

curl -sLo "$tmp" "$latest" ||
  die "failed to download" "$tmp"

tar -xzf "$tmp" --strip-components=1 -C "$NVIM_PREFIX" 2>/dev/null ||
  die "failed to extract into '$NVIM_PREFIX' (use sudo?)" "$tmp"

rm -rf "$tmp" ||
  die "failed to delete '$tmp'"

ln -sf "$NVIM_PREFIX"/bin/nvim "$NVIM_PREFIX"/bin/vim ||
  die "failed to create symbolic link"
