#!/bin/sh
PKG_LIST="${PKG_LIST:-$XDG_CONFIG_HOME/packages/cargo/list}"

_tc="$(rustup show active-toolchain)"
if [ -z "$_tc" ]; then
  echo "[rust] no default toolchain; setting stable"
  rustup default stable
fi

if ! [ -f "$PKG_LIST" ]; then
  echo "No package list found at PKG_LIST=$PKG_LIST"
  exit 1
fi

while read l; do
  pkg="${l%%#*}"
  if [ "$pkg" != "" ]; then
    case "$pkg" in
    *https://*) cargo install $pkg --locked ;;
    *) cargo install "$pkg" --locked ;;
    esac
  fi
done <"$PKG_LIST"
