#!/bin/sh

printf ' %s\n' "--------------"
printf ' \e[1m%s\e[0m\n' "SETUP - neovim"
printf ' %s\n' "--------------"

NVIM_PREFIX="${NVIM_PREFIX:-"/usr/local"}"

archive="nvim-linux-x86_64.tar.gz"
latest="https://github.com/neovim/neovim/releases/latest/download/$archive"

die() {
  [ -f "$1" ] && rm -rf "$1"
  exit 1
}

set -x

[ -d "$NVIM_PREFIX" ] || die

tmp="$(mktemp)" || die

curl -fsSL -o "$tmp" "$latest" || die "$tmp"

tar -xzf "$tmp" --strip-components=1 -C "$NVIM_PREFIX" 2>/dev/null ||
  die "$tmp"

rm -rf "$tmp" ||
  die

ln -sf "$NVIM_PREFIX"/bin/nvim "$NVIM_PREFIX"/bin/vim ||
  die
