#!/bin/sh

printf ' %s\n' "--------------"
printf ' \e[1m%s\e[0m\n' "SETUP - c3lang"
printf ' %s\n' "--------------"

C3_PREFIX="${C3_PREFIX:-"$HOME/.local"}"

archive="c3-linux.tar.gz"
latest="https://github.com/c3lang/c3c/releases/latest/download/$archive"

die() {
  [ -d "$1" ] && rm -rf "$1"
  exit 1
}

set -x

[ -d "$C3_PREFIX" ] || die

tmp="$(mktemp -d)" || die

curl -fsSL -o "$tmp"/"$archive" "$latest" || die "$tmp"

(
  cd "$tmp" &&
    tar -xzf "$archive" &&
    install -d "$C3_PREFIX"/bin "$C3_PREFIX"/lib &&
    install -m 755 c3/c3c "$C3_PREFIX"/bin/ &&
    cp -r c3/lib/. "$C3_PREFIX"/lib/
) || die "$tmp"

rm -rf "$tmp" || die
