#!/bin/sh
EXPORTS_BIN_PREFIX="$HOME/.local/bin"
FLATPAK_BIN_PREFIX="/var/lib/flatpak/exports/bin"
FLATPAK_LIST="$XDG_CONFIG_HOME"/packages/flatpak/list.yml

if ! [ -d "$EXPORTS_BIN_PREFIX" ]; then
  mkdir -p "$EXPORTS_BIN_PREFIX"
fi

while read line; do
  if [ -z "${line%%\#*}" ]; then
    continue
  fi

  bin="${line%%:*}"
  app="${line##*:}"
  app="${app##* }"

  if [ "$bin" != "" ]; then
    ln -sf "$FLATPAK_BIN_PREFIX"/"$app" "$EXPORTS_BIN_PREFIX"/"$bin"
  fi

  app_list="$app_list $app"
done <"$FLATPAK_LIST"

flatpak install -y $app_list
