# -*- ispell-local-dictionary: "en"; -*-
#+title: Custom Doom Emacs Config

** Appearance

This setting determines the line number style in effect. Setting it to ~nil~ disables line numbers. For relative line numbers, set it to ~relative~.

#+begin_src elisp
(setq display-line-numbers-type t)
#+end_src

#+begin_src elisp
(setq doom-theme 'doom-one)
#+end_src

*** Fonts

#+begin_src elisp
(setq doom-font (font-spec :family "Iosevka" :size 16 :weight 'medium :antialias 'subpixel))
(setq doom-variable-pitch-font (font-spec :family "Iosevka Etoile" :size 14 :weight 'medium :antialias 'subpixel))
#+end_src

** Spell checking

Use Spanish by default, although one can override this by setting: ~# -*- ispell-local-dictionary: "en"; -*-~ on top of a file.

#+begin_src elisp
(setq ispell-dictionary "es")
#+end_src

** Org mode

#+begin_src elisp
(setq org-directory "~/Documents/")
(setq org-agenda-files '("~/Documents/agenda/"))

(after! org-agenda
  (setq org-agenda-span 'week
        org-agenda-start-on-weekday 1
        org-agenda-start-day nil))
#+end_src

** RSS

#+begin_src elisp
(setq rmh-elfeed-org-files '("rss/news.org"
                             "rss/youtube.org"))
#+end_src

The files above are resolved relative to ~org-directory~, so they point to
~/Documents/rss/news.org~ and ~/Documents/rss/youtube.org~.

This will allow syntax highlighting in math equations and other latex environments inside Org mode.

#+begin_src elisp
(setq org-highlight-latex-and-related '(native script entities))
#+end_src

#+begin_src elisp
(add-hook 'org-mode-hook #'doom-disable-line-numbers-h)
#+end_src

*** Writeroom mode

~writeroom-mode~ is a distraction-free mode for buffers meant mainly for writing. It uses ~mixed-pitch-mode~, but it doesn't use the height already set with ~doom-font~ and ~doom-variable-pitch-font~. In order to change this, we set:

#+begin_src elisp
(setq mixed-pitch-set-height t)
#+end_src

When enabling ~writeroom-mode~, the default text scaling is ~2~ but we would like to use ~1.5~. Also, the default width is too wide, so, we customize the default behavior:

#+begin_src elisp
(setq +zen-text-scale 1.5)
(setq writeroom-width 40)
#+end_src

Finally, auto-enable this mode when entering ~org-mode~:

#+begin_src elisp
(add-hook 'org-mode-hook #'writeroom-mode)
#+end_src

** Citations

#+begin_src elisp
(setq citar-bibliography (list (expand-file-name "~/Documents/bibliography.bib"))
      org-cite-csl-styles-dir (expand-file-name "~/.config/zotero/styles"))
#+end_src

** Email

We make email sync the moment we open ~mu4e~, I don't like background sync. Additionally, set the proper XDG-compliant folder for isync-synced email.

#+begin_src elisp
(after! mu4e
  (add-hook 'mu4e-main-mode-hook
            (lambda ()
              (mu4e-update-mail-and-index t))))

(setq mu4e-maildir (expand-file-name "~/.local/share/isync")
      mu4e-get-mail-command "mbsync -a"
      mu4e-update-interval nil)
#+end_src

#+begin_src elisp
(setq +mu4e-gmail-accounts '(("gustavo.calvo.cr@gmail.com" . "personal")))

(set-email-account! "personal"
                    '((user-full-name . "Gustavo Calvo")
                      (user-mail-address . "gustavo.calvo.cr@gmail.com")
                      (mu4e-sent-folder . "/personal/[Gmail]/Sent Mail")
                      (mu4e-drafts-folder . "/personal/[Gmail]/Drafts")
                      (mu4e-trash-folder . "/personal/[Gmail]/Trash")
                      (mu4e-refile-folder . "/personal/[Gmail]/All Mail")
                      (smtpmail-smtp-user . "gustavo.calvo.cr@gmail.com")
                      (smtpmail-smtp-server . "smtp.gmail.com")
                      (smtpmail-smtp-service . 587)
                      (smtpmail-stream-type . starttls)
                      (smtpmail-servers-requiring-authorization . "smtp\\.gmail\\.com"))
                    t)
#+end_src

#+begin_src elisp
(set-email-account! "ucr"
                    '((user-full-name . "Gustavo Calvo")
                      (user-mail-address . "gustavo.calvogutierrez@ucr.ac.cr")
                      (mu4e-sent-folder . "/ucr/Enviado")
                      (mu4e-drafts-folder . "/ucr/Borradores")
                      (mu4e-trash-folder . "/ucr/Papelera")
                      (mu4e-trash-without-flag . t)
                      (mu4e-refile-folder . "/ucr/Archive")
                      (smtpmail-smtp-user . "gustavo.calvogutierrez@ucr.ac.cr")
                      (smtpmail-smtp-server . "smtp.ucr.ac.cr")
                      (smtpmail-smtp-service . 587)
                      (smtpmail-stream-type . starttls)
                      (smtpmail-servers-requiring-authorization . "smtp\\.ucr\\.ac\\.cr"))
                    nil)
#+end_src

** LaTeX export

#+begin_src elisp
(after! ox-latex
  (setq org-latex-pdf-process '("tectonic -o %o %f")
        org-latex-remove-logfiles t)
  (add-to-list 'org-latex-logfiles-extensions "tex"))
#+end_src
