# -*- ispell-local-dictionary: "en"; -*-
#+title: Custom Doom Emacs Config

** Appearance

This setting determines the line number style in effect. Setting it to ~nil~ disables line numbers. For relative line numbers, set it to ~relative~.

#+begin_src elisp
(setq display-line-numbers-type t)
#+end_src

#+begin_src elisp
(setq doom-theme 'doom-one)
#+end_src

*** Fonts

#+begin_src elisp
(setq doom-font (font-spec :family "Iosevka" :size 16 :weight 'medium :antialias 'subpixel))
(setq doom-variable-pitch-font (font-spec :family "Iosevka Etoile" :size 14 :weight 'medium :antialias 'subpixel))
#+end_src

** Spell checking

Use Spanish by default, although one can override this by setting: ~# -*- ispell-local-dictionary: "en"; -*-~ on top of a file.

#+begin_src elisp
(setq ispell-dictionary "es")
#+end_src

** Org mode

#+begin_src elisp
(setq org-directory "~/Documents/")
(setq org-agenda-files '("~/Documents/agenda/"))
#+end_src

#+begin_src elisp
(add-hook 'org-mode-hook #'doom-disable-line-numbers-h)
#+end_src

*** Writeroom mode

~writeroom-mode~ is a distraction-free mode for buffers meant mainly for writing. It uses ~mixed-pitch-mode~, but it doesn't use the height already set with ~doom-font~ and ~doom-variable-pitch-font~. In order to change this, we set:

#+begin_src elisp
(setq mixed-pitch-set-height t)
#+end_src

When enabling ~writeroom-mode~, the default text scaling is ~2~ but we would like to use ~1.5~. Also, the default width is too wide, so, we customize the default behavior:

#+begin_src elisp
(setq +zen-text-scale 1.5)
(setq writeroom-width 40)
#+end_src

Finally, auto-enable this mode when entering ~org-mode~:

#+begin_src elisp
(add-hook 'org-mode-hook #'writeroom-mode)
#+end_src
