#!/bin/sh
PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
GNUPGHOME="$HOME/.local/share/gnupg"

password="$(~/.config/scripts/menu/menu-pass)"
[ -z "$password" ] && exit
xdotool type $(pass "$password" | head -n 1)
