$mod = SUPER

$left = h
$down = j
$up = k
$right = l

$term = foot
$menu = bemenu-run -p "Run" | xargs -r hyprctl dispatch exec
$power = printf 'poweroff\nreboot\n' | bemenu -p Power | xargs sh -c
$pass = ~/.config/scripts/passmenu
$passotp = ~/.config/scripts/passmenu otp
$sound = foot -T floating-wiremix wiremix
$wifi = foot -T floating-impala impala
$bluetooth = foot -T floating-bluetui bluetui
$filemanager = nautilus
$browser = ${BROWSER:-firefox}
$volup = wpctl set-volume @DEFAULT_SINK@ 5%+ && wpctl set-mute @DEFAULT_SINK@ 0
$voldown = wpctl set-volume @DEFAULT_SINK@ 5%- && wpctl set-mute @DEFAULT_SINK@ 0
$mute = wpctl set-mute @DEFAULT_SINK@ toggle
$micup = wpctl set-volume @DEFAULT_SOURCE@ 5%+ && wpctl set-mute @DEFAULT_SOURCE@ 0
$micdown = wpctl set-volume @DEFAULT_SOURCE@ 5%- && wpctl set-mute @DEFAULT_SOURCE@ 0
$micmute = wpctl set-mute @DEFAULT_SOURCE@ toggle
$brightup = brightnessctl s 5%+
$brightdown = brightnessctl s 5%-
$prt = ~/.config/scripts/prtsc
$colorpicker = ~/.config/scripts/colorpicker
