# https://wiki.hypr.land/Configuring/Variables/#input
input {
    repeat_delay = 300
    repeat_rate = 70
}

input {
    kb_layout = us,latam
    kb_variant =
    kb_model =
    kb_options = grp:alt_space_toggle
    kb_rules =
}
