# https://wiki.hypr.land/Configuring/Variables/#input
input {
    touchpad {
        natural_scroll = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
