misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

# Ignore maximize requests from all apps. You'll probably like this.
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# Disable launcher animation for bemenu's layer-shell surface.
layerrule {
    name = no-bemenu-animation
    match:namespace = ^menu$
    no_anim = true
}

# "Smart gaps" / "No gaps when only"
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule {
    name = no-gaps-wtv1
    match:float = false
    match:workspace = w[tv1]

    border_size = 0
    rounding = 0
}
windowrule {
    name = no-gaps-f1
    match:float = false
    match:workspace = f[1]
    border_size = 0
    rounding = 0
}
