#!/bin/sh
FUNC="$1"
MODE="$2"

all() {
    printf "\033[1m\033[34m=== %s ===\033[0m\n%s\n" "$DATE" "$(calcurse -a -t)"
}

apts() {
    [ -z "$MODE" ] && apts="$(calcurse -a)"
    [ "$MODE" = "count" ] && apts="$(calcurse -a | grep -c '\*')"
    if [ "$apts" = "0" -o "$apts" = "" ] ; then return 0 ; fi
    echo "󰃭 $apts"
}

todo() {
    [ -z "$MODE" ] && todo="$(calcurse -t)"
    [ "$MODE" = "count" ] && todo="$(calcurse -t | wc -l)"
    if [ "$todo" = "0" -o "$todo" = "" ] ; then return 0 ; fi
    echo " $todo"
}

[ -z "$FUNC" ] && all && exit 0
$FUNC $MODE
