#!/bin/sh
# Script for 'pass'

# Ask for password name in vault
password=$(find $XDG_DATA_HOME/password-store/ -type f -name '*.gpg' |
	sed 's/.*\/\(.*\)\.gpg$/\1/' | dmenu -i -p "Password:")

# Exit if none chosen
[ -z "$password" ] && exit

# If chosen, use xdotool to type it
xdotool type "$(pass $password | head -1)" && [ -e /usr/bin/notify-send ] && notify-send " $password" "Successfully decrypted"
