#!/bin/sh
# Prompt for power options using dmenu

option=$(printf "Shutdown\nRestart" | dmenu -i -p "Power:")

case "$option" in
	"Shutdown") sudo poweroff ;;
	"Restart") sudo reboot ;;
	*) exit 1 ;;
esac

