#!/bin/sh
# Get URL from clipboard
# and save as a bookmark

bookmark="$(xsel -ob)"

if grep -q "$bookmark" "$HOME/Documents/bookmarks" ; then
    notify-send "󰃀 Bookmarks" "Already bookmarked"
else
    name="$(dmenu -p 'Bookmark name:' < /dev/null)"
    entry="$name-$bookmark"
    echo "$entry" >> "$HOME/Documents/bookmarks"
    notify-send "󰃀 Bookmarks" "Added '$entry'"
fi
