#!/bin/sh
# OTP script for 'pass'

# Ask for password name in vault
password=$(find ~/.password-store/ -type f -name '*.gpg' | sed 's/.*\/\(.*\)\.gpg$/\1/' | dmenu -i -p "OTP:")

# Exit if none chosen
[ -z "$password" ] && exit

# Otherwise, copy to clipboard and notify OTP
pass otp "$password" | while read -r OUTPUT; do
    echo $OUTPUT | xsel -ib
    xdotool type "$OUTPUT"
    notify-send " $password" "$OUTPUT"
done
