#!/bin/sh
PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
GNUPGHOME="$HOME/.local/share/gnupg"

password="$(~/.config/scripts/menu/menu-pass)"
if [ "$?" != 0 ] || [ -z "$password" ] ; then
    exit 1
fi

xdotool type $(pass "$password" | head -n 1)
