#!/bin/sh

case $1 in
    *.tar.bz2)  tar vxjf $1     ;;
    *.tar.zst)  unzstd $1       ;;
    *.tar.xz)   tar vxf $1      ;;
    *.tar.gz)   tar vxzf $1     ;;
    *.tbz2)     tar vxjf $1     ;;
    *.tar)      tar vxf $1      ;;
    *.rar)      unrar x $1      ;;
    *.zip)      unzip $1        ;;
    *.deb)      ar x $1         ;;
    *.bz2)      bunzip2 $1      ;;
    *.tgz)      tar vxzf $1     ;;
    *.7z)       7z x $1         ;;
    *.gz)       gunzip $1       ;;
    *.xz)       unxz $1         ;;
    *.Z)        uncompress $1   ;;
    *) echo "Usage: extract <file>" ;;
esac
