#!/bin/sh
prog="$0"
inputs="$@"

error() {
  printf '\e[2m[%s]\e[0m \e[31merror:\e[0m %s\n' "$prog" "$1"
}

for input in $inputs; do
  if ! [ -f "$input" ]; then
    error "bad file '$input'"
    continue
  fi

  _ext="${input##*.}"
  _base="${input%.*}"
  output="$_base-stab.$_ext"

  if ! trf="$(mktemp)"; then
    error "cannot create temp transforms file"
    continue
  fi

  if [ -z "$trf" ] || ! [ -f "$trf" ]; then
    error "bad temp transforms file '$trf'"
    continue
  fi

  echo "stabilizing: $input -> $output"

  if ! codec=$(ffprobe -v error \
    -select_streams v:0 \
    -show_entries stream=codec_name \
    -of default=noprint_wrappers=1:nokey=1 \
    "$input"); then
    die "failed to get codec"
  fi

  if ! ffmpeg -y -i "$input" -vf vidstabdetect=shakiness=10:accuracy=15:result="$trf" -f null -; then
    error "failed to detect movement"
    continue
  fi

  if ! ffmpeg -y -i "$input" -vf vidstabtransform=input="$trf" -c:v "$codec" "$output"; then
    error "failed to stabilize video"
    continue
  fi

  rm -f "$trf"
done
