#!/bin/sh
PROG="$0"
input="$1"
log=".stab.log"

die() {
  printf '\e[2m[%s]\e[0m \e[31merror:\e[0m %s\n' "$PROG" "$1"
  exit 1
}

if ! [ -f "$input" ]; then
  die "bad file '$input'"
fi

_ext="${input##*.}"
_base="${input%.*}"
output="$_base-stab.$_ext"

trf="$(mktemp)" || die "cannot create temp transforms file"

if [ -z "$trf" ] || ! [ -f "$trf" ]; then
  die "bad temp transforms file '$trf'"
fi

echo "stabilizing: $input -> $output"

codec=$(ffprobe -v error \
  -select_streams v:0 \
  -show_entries stream=codec_name \
  -of default=noprint_wrappers=1:nokey=1 \
  "$input") || die "failed to get codec"

ffmpeg -y -i "$input" -vf vidstabdetect=shakiness=10:accuracy=15:result="$trf" -f null - >>"$log" 2>&1 ||
  die "failed to detect movement"

ffmpeg -y -i "$input" -vf vidstabtransform=input="$trf" -c:v "$codec" "$output" >>"$log" 2>&1 ||
  die "failed to stabilize video"

rm -f "$trf" "$log"
