#!/bin/sh

# Get branch info
echo "Branch name: " && read -r branch
[ -z "$branch" ] && echo "No branch name specified" && exit
echo "Branch origin (blank for 'origin'): " && read -r origin

# Create branch and switch to it
git checkout -b "$branch"

# Push changes from origin
[ -z "$origin" ] && origin="origin"
git push --set-upstream "$origin" "$branch"
