#!/bin/sh
#
# Small compiler script for groff
#
# [-k (preconv)] Convert encoding to something groff understands
# [-e (eqn)]     Format equations for troff or MathML
# [-t (tbl)]     Format tables for troff
# [-p (pic)]     Compile pictures for troff or TeX
# [-G (grap)]    Typesetting graphs
# [-j (chem)]    Chemical structure diagrams (messes up spacing!)

# Configuration
BIB="~/Desktop/bibliography" # Bibliography file
MAC="~/.config/groff/"       # Macros dir
PRE="ketp"                   # Preprocessors

# Enable macros, grab references, include args
soelim -I "$MAC" "$1" | refer -p "$BIB" |
    groff -mspdf -T pdf -U -"$PRE"

