#!/bin/sh
HOST="$1"

print_yes() {
    printf '\033[2m%s:\033[0m \033[1m\033[32mYES\033[0m\n' "$1"
}
print_no() {
    printf '\033[2m%s:\033[0m \033[1m\033[31mNO\033[0m\n' "$1"
}

if ! ping -c 1 "$HOST" > /dev/null 2>&1; then
    print_no DNS
    print_no WEB
else
    print_yes DNS
    curl --silent --fail "$HOST" > /dev/null 2>&1 &&
        print_yes WEB || print_no WEB
fi
