#!/bin/sh
# Copy snippets to clipboard

# Snippets directory
snippets=~/Documents/snippets
# Select using menu, copy if successful
snippet=$(ls "$snippets" | menu "Snippet:")

# Exit if empty
[ -z "$snippet" ] && exit

# Copy to clipboard and notify otherwise
printf '%s' "$(cat $snippets/$snippet)" |
    xsel -ib && notify-send "Snippet" "'$snippet' copied to clipboard!"
