#!/bin/sh
emoji="$HOME/.config/emoji"

if ! [ -f "$emoji" ]; then
  echo "no emoji file"
  exit 1
fi

chosen="$(while read line; do
  echo "$line"
done <"$emoji" | menu dmenu)"
chosen="${chosen%% *}"

if [ -n "$chosen" ]; then
  echo "$chosen"
fi
