#!/bin/sh
PACKAGE_MANAGER_DIR="${PACKAGE_MANAGER_DIR:-$XDG_CONFIG_HOME/pm}"

error() {
  printf '[%s] %s' "ERROR" "$1"
}

if ! command -v make >/dev/null 2>&1; then
  error "'make' not found in \$PATH"
  exit 1
fi

(cd "$PACKAGE_MANAGER_DIR" && make $@)
