#!/bin/sh
FOLDER="$1"
STYLE="$2" # moody_bw, teal

# Configs
EXTENSION="jpg"
LONG_EDGE=1920
QUALITY=89

darktable-cli \
    --import "$FOLDER" \
    --width "$LONG_EDGE" \
    --height "$LONG_EDGE" \
    --out-ext ".$EXTENSION" \
    --style "$STYLE" \
    "${FOLDER%%/}/darktable_export/IMG.jpg" \
    --core --conf plugins/imageio/format/jpeg/quality=$QUALITY \

