#!/bin/sh

printf ' %s\n' "-------------------"
printf ' \e[1m%s\e[0m\n' "SETUP - anypinentry"
printf ' %s\n' "-------------------"

raw="https://raw.githubusercontent.com/tavocg/anypinentry/refs/heads/master"
PREFIX="/usr/local"

set -ex

[ -d "$PREFIX" ]

for p in menu anypinentry; do
  curl -fsSL "$raw/$p" -o "$PREFIX/$p"
  chmod +x "$PREFIX/$p"
done

if [ -d /etc/alternatives ]; then
  ln -sf "$PREFIX/anypinentry" /etc/alternatives/pinentry
fi
