#!/bin/sh

# See:
# https://docs.docker.com/engine/install/debian/

printf ' %s\n' "-----------------------"
printf ' \e[1m%s\e[0m\n' "SETUP - docker (debian)"
printf ' %s\n' "-----------------------"

set -ex

for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do apt-get remove -y $pkg >/dev/null 2>&1; done

# Add Docker's official GPG key:
apt-get update -y >/dev/null 2>&1
apt-get install -y ca-certificates curl >/dev/null 2>&1
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
  tee /etc/apt/sources.list.d/docker.list >/dev/null
apt-get update >/dev/null 2>&1

apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null 2>&1

set +x

echo ' Run:'
echo '   sudo usermod -a -G docker $USER'
