#!/bin/sh

printf ' %s\n' "-----------------"
printf ' \e[1m%s\e[0m\n' "SETUP - NERD FONT"
printf ' %s\n' "-----------------"

RELEASE_URL="https://github.com/ryanoasis/nerd-fonts/releases/latest/download"
FONTS_PREFIX="/usr/local/share/fonts"
NERD_FONT="${NERD_FONT:-JetBrainsMono}"

_out_dir="$FONTS_PREFIX"/"$NERD_FONT"

set -ex

mkdir -p "$_out_dir"

curl -fsSL "$RELEASE_URL"/"$NERD_FONT".tar.xz |
  tar xJf - --directory="$_out_dir" --wildcards '*.ttf'
