#!/bin/sh

printf ' %s\n' "------------------------"
printf ' \e[1m%s\e[0m\n' "SETUP - nvidia (flatpak)"
printf ' %s\n' "------------------------"

set -e

systemversion=
nvidia-smi --version | while read line; do
  case "$line" in
  DRIVER*)
    FOUND_NV_DRIVER=1
    systemversion="${line#*: }" systemversion="${systemversion%% *}" # 550.163.01
    firstnumber="${systemversion%%.*}"
    secondnumber="${systemversion#*.}" secondnumber="${secondnumber%.*}"
    thirdnumber="${systemversion##*.}"
    systemversion="$firstnumber-$secondnumber-$thirdnumber" # 550-163-01

    set -x
    flatpak install "org.freedesktop.Platform.GL.nvidia-$systemversion" >/dev/null 2>&1
    break
    ;;
  *) ;;
  esac
done
