#!/usr/bin/env bash

printf ' %s\n' "---------------"
printf ' \e[1m%s\e[0m\n' "SETUP - LazyVim"
printf ' %s\n' "---------------"

set -ex

for dir in ~/.config/nvim ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim ~/.local/cache/nvim; do
  if [ -d "$dir" ]; then
    mv "$dir"{,.bak}
  fi
done

git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git
git -C ~/.config restore nvim
