#!/bin/sh

help() {
    printf "\033[2mUsage:\033[0m share [DIRECTORY/FILE]\n"
    exit 0
}

LOC="$1" ; [ -n "$LOC" ] || help
TEMP_DIR="/tmp/sharedir"

[ -d "$LOC" ] && DIR="$LOC" || DIR="$TEMP_DIR"
[ "$DIR" = "$TEMP_DIR" ] && mkdir -p "$TEMP_DIR" && cp -f "$LOC" "$DIR/"

python -m http.server -b 0.0.0.0 8000 -d "$DIR"
[ "$DIR" = "$TEMP_DIR" ] && rm -rf "$DIR"
