#!/bin/sh
NULL_PTR="https://0x0.st"

LOC="$1"
FILE="${LOC%/}.zip"
zip -r "$FILE" "$LOC"
zipcloak "$FILE"

curl -F "file=@$FILE" "$NULL_PTR"

printf 'Remove created %s? [y/n]: ' "$FILE" && read p
[ "$p" = "y" ] && rm -rf "$FILE"

exit 0
