#!/bin/sh

if [ "$(tty)" = "/dev/tty1" ] && [ "$LOAD_DESKTOP" ] && [ -z "$DISPLAY" ]; then
  # Give time to stop via SIGINT
  # Also, sway startup misbehaves without this
  sleep 0.2

  case "$XDG_SESSION_DESKTOP" in
  kde)
    exec /usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland
    ;;
  dwm)
    amixer &
    XDG_SESSION_DESKTOP=dwm XDG_SESSION_TYPE=x11 GDK_BACKEND=x11 exec startx
    ;;
  i3)
    amixer &
    XDG_SESSION_DESKTOP=i3 XDG_SESSION_TYPE=x11 GDK_BACKEND=x11 exec startx
    ;;
  sway)
    XDG_SESSION_DESKTOP=sway XDG_SESSION_TYPE=wayland GDK_BACKEND=wayland exec sway
    ;;
  *) echo "error: current \$XDG_SESSION_DESKTOP not supported (kde, dwm, i3, sway)" ;;
  esac
fi
