#!/bin/sh

if [ "$(tty)" = "/dev/tty1" ] && [ "$LOAD_DESKTOP" ] && [ -z "$DISPLAY" ]; then
  case "$XDG_SESSION_DESKTOP" in
  kde)
    exec /usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland
    ;;
  dwm)
    sleep 0.5
    amixer &
    XDG_SESSION_DESKTOP=dwm XDG_SESSION_TYPE=x11 GDK_BACKEND=x11 exec startx
    ;;
  sway)
    XDG_SESSION_DESKTOP=sway XDG_SESSION_TYPE=wayland GDK_BACKEND=wayland exec sway
    ;;
  *) echo "error: current \$XDG_SESSION_DESKTOP not supported (kde, dwm, sway)" ;;
  esac
fi
