#!/bin/sh
once="$1"
separator="    "

get_layout_sway() {
  layout="$(swaymsg -t get_inputs | grep -m 1 'xkb_active_layout_name' | cut -d '"' -f 4)"
  [ "$layout" = "English (US)" ] && layout="us"
  [ "$layout" = "Spanish (Latin American)" ] && layout="la"
  echo "󰌌 $layout"
}

get_layout_x11() {
  setxkbmap -query | awk '/layout/{ print $2 }' | sed 's/latam/la/'
}

get_layout() {
  if [ "$XDG_SESSION_TYPE" = "x11" ]; then
    get_layout_x11
    return 0
  fi

  case "$XDG_SESSION_DESKTOP" in
  sway) get_layout_sway ;;
  *) return 1 ;;
  esac
}

while true; do
  status=""

  volume="$(volstat)"
  ! [ -z "$volume" ] && status="$status$separator$volume"

  microphone="$(micstat)"
  ! [ -z "$microphone" ] && status="$status$separator$microphone"

  cpu="$(cpustat)"
  ! [ -z "$cpu" ] && status="$status$separator $cpu"

  ram="$(memorystat)"
  ! [ -z "$ram" ] && status="$status$separator $ram"

  network="$(netstat)"
  ! [ -z "$network" ] && status="$status$separator$network"

  battery="$(batstat)"
  ! [ -z "$battery" ] && status="$status$separator$battery"

  layout="$(get_layout)"
  ! [ -z "$layout" ] && status="$status$separator$layout"

  date_time="$(date "+%I:%M%p$separator󰃮 %a %Y-%m-%d")"
  ! [ -z "$date_time" ] && status="$status$separator󰥔 $date_time"

  printf "%s\n" "$status"

  if [ -n "$once" ]; then
    exit 0
  fi

  sleep 0.4
done
